### ISSUE TITLE
formal properties fail

### ISSUE THREAD

**Issue by mattvenn** [etalian/mensa.wip#4]
missing files, or outdated paths?
![image](https://user-images.githubusercontent.com/634220/122044511-e1d0f880-cddc-11eb-91eb-39d3f2420fb8.png)

**Comment by etalian** [comment]
Fixed the paths, however sby complains about syntax errors in properties.v, which has not been touched...

https://gitlab.com/etalian/mensa.wip/-/jobs/1349375416

**Comment by etalian** [comment]
Fixed.
